name: stats
on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch: # Allow for running this manually.

jobs:
  generate-stats:
    name: github-repo-stats
    runs-on: ubuntu-latest
    steps:
      - name: github-repo-stats
        uses: jgehrcke/github-repo-stats@v1.3.0
        with:
          ghpagesprefix: https://xbase-lab.github.io/stats
          repository: xbase-lab/xbase
          databranch: master
          ghtoken: ${{ secrets.ghrs_github_api_token }}
